### ISSUE TITLE
%{keyword} expansion fails for :template-file

### ISSUE THREAD

**Issue by jsturdy** [progfolio/doct#21] opened 2020-09-06 16:52 UTC
## Describe the problem
I've been trying to track down why a template file I have wasn't expanding the `%{doct-keyword}` like it seemed it should, based on the description of the functionality.

I moved the template into the `:template` call itself and the expansion happened as advertised, but if my template lives in a file, and is expanded through `:template-file`, the `%{doct-keyword}` fields all show up as `%{doct-keyword}`

I haven't been able to find anything in the documentation that says what I'm hoping to accomplish shouldn't work (and it's easily possible that my limited `elisp` is to blame)

## Directions to reproduce

Create the template file (`/tmp/org-test/templates/task-`) with the content:
```org
* %{todo-state} %^{Description}
%^{timetype|DEADLINE:|SCHEDULED:} %^t
:PROPERTIES:
:ID: %^{ID|%(car (process-lines "uuidgen"))}
:CREATED: %U
:LASTUPDATED: %U
:SPECIAL: %{other-key}
:SOURCE: %{source-template}
:END:
%?

```

Evaluate the following (probably relies on having set up `org-capture` and `doct`, for me the `setq` is inside the `:config` portion of my `(use-package doct)` call)
```lisp

(defvar my/org-dir
  "/tmp/org-test")

(defvar my/org-template-dir
  (expand-file-name "templates" my/org-dir))

(defvar my/org-capture-inbox-file
  (expand-file-name "inbox.org" my/org-dir))

(setq org-capture-templates
      (doct `(("Tasks" :keys "t" :headline "Tasks"
               :prepend t
               :empty-lines 1
               :immediate-finish t
               :source-template "in-place"
               :file my/org-capture-inbox-file
               :template ("* %{todo-state} %^{Description}"
                          "%^{timetype|DEADLINE:|SCHEDULED:} %^t"
                          ":PROPERTIES:"
                          ":ID: %^{ID|%(car (process-lines \"uuidgen\"))}"
                          ":CREATED: %U"
                          ":LASTUPDATED: %U"
                          ":SPECIAL: %{other-key}"
                          ":SOURCE: %{source-template}"
                          ":END:"
                          "%?")
               :children (("To-do"     :keys "t" :todo-state "TODO"  :other-key "this will work")
                          ("Next"      :keys "n" :todo-state "NEXT"  :other-key "this will work")
                          ("Done"      :keys "d" :todo-state "DONE"  :other-key "this will work")
                          ("Cancelled" :keys "x" :todo-state "CANCELLED"  :other-key "this will work")))
              ("Task template file" :keys "T" :headline "Tasks"
               :prepend t
               :empty-lines 1
               :immediate-finish t
               :file js/org-capture-inbox-file
               :source-template "file"
               :template-file ,(expand-file-name "task-template.org" my/org-template-dir)
               :children (("To-do"     :keys "t" :todo-state "TODO" :other-key "this will not work")
                          ("Next"      :keys "n" :todo-state "NEXT" :other-key "this will not work")
                          ("Done"      :keys "d" :todo-state "DONE" :other-key "this will not work")
                          ("Cancelled" :keys "x" :todo-state "CANCELLED" :other-key "this will not work"))))))
```

Capturing with `C-c c t t` results in:
```org
** TODO Doct template inline
   DEADLINE: <2020-09-06 Sun>
   :PROPERTIES:
   :ID:       b4b9a8a1-25c0-4731-af71-cb18e3f89f4f
   :CREATED:  [2020-09-06 Sun 18:46]
   :LASTUPDATED: [2020-09-06 Sun 18:46]
   :SPECIAL:  this will work
   :SOURCE:   in-place
   :END:
```  

Capturing with `C-c c T t` (using the template file) results in:
```org
** %{todo-state} Doct template from file
   DEADLINE: <2020-09-06 Sun>
   :PROPERTIES:
   :ID:       6e8ab07a-a273-47e8-b41a-6aff99b86f16
   :CREATED:  [2020-09-06 Sun 18:46]
   :LASTUPDATED: [2020-09-06 Sun 18:46]
   :SPECIAL:  %{other-key}
   :SOURCE:   %{source-template}
   :END:
```
Note that the three `%{doct-keyword}` placeholders are not picking up their keyword values from the config.

Apologies if this is a result of my incorrect application of `doct` or `elisp`, but I thought that since I was able to seemingly isolate it to whether the template comes from `:template` or from `:template-file`, it would be worth it to create an issue.
Thanks for your work in putting together this very useful package!

### Version information

* Emacs version: 
```
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-28
```
* Org mode version: 
```
Org mode version 9.3.7 (release_9.3.7-705-gea9463 @ mixed installation! /usr/share/emacs/27.1/lisp/org/ and /home/${USER}/.config/emacs/straight/build/org/)
```
* Operating system: Arch linux, kernel version `5.8.5-arch1-1`

**Comment by progfolio** [comment] 2020-09-06 19:10
>  Thanks for your work in putting together this very useful package!

I'm glad you're finding it useful. Thank you for the detailed report.

> Apologies if this is a result of my incorrect application of doct or elisp, but I thought that since I was able to seemingly isolate it to whether the template comes from :template or from :template-file, it would be worth it to create an issue.

No apology necessary. Your analysis is correct. The expansion was not happening for `:template-file` strings.
Oversight on my part. I've pushed a fix on the latest master branch. Would you mind updating and testing it out?

**Comment by progfolio** [comment] 2020-09-06 20:46
Off-topic side note:

> Org mode version 9.3.7 (release_9.3.7-705-gea9463 @ mixed installation! /usr/share/emacs/27.1/lisp/org/ and /home/${USER}/.config/emacs/straight/build/org/)

Your Org installation is mixed. This has nothing to do with what you're experiencing with doct, but it can cause very subtle and hard to track bugs. Part of this is due to the way straight.el currently handles fixing Org (it implements a workaround to make up for not running the necessary make commands building Org requires). I have an outstanding pull I've been working on that aims to solve this by enabling recipes to run commands before (and after) straight byte-compiles, symlinks, etc:

https://github.com/raxod502/straight.el/pull/535

I've been using it on my laptop and it works so far, but I'm sure it needs more testing.
Here's the branch if you're feeling adventurous:

https://github.com/progfolio/straight.el/tree/feat/support-arbitrary-build-commands-72

**Comment by jsturdy** [comment] 2020-09-06 22:05
This does indeed fix the `%{keyword}` expansion, however, it now seems to uncover two other issues:
* that only the last `:template-file` is used for all occurrences
* mixing `:template-file` and `:template` breaks some items, and introduces some dependence on whether `:template-file` occurs before `:template` or not.

If the snippet I had above was the first entry, and I had a last entry like:
```lisp
                ("Meeting Notes" :keys "m" :headline "Meetings"
                 :prepend t
                 :empty-lines 1
                 :clock-in t
                 :clock-resume t
                 :file "/tmp/meeting-notes-test.org"
                 :template-file ,(expand-file-name "meeting-notes-template.org" my/org-template-dir))
```
every capture entry that uses `:template-file` picks up `meeting-notes-template.org` as the template.

When adding back in all my capture templates, I got the error message :
```
org-capture: Capture template ‘tt’: Template is not a valid Org entry or tree
```
I *think* this is somehow a conflict between entries having a `:template` which is inline in the config, and other entries taking their templates from a `:template-file` (and possibly the order in which those entries are parsed)

I pared down my call to `doct` to include only two very simple templates and was able to reliably reproduce these two issues.

#### Baseline
As a starting point, this works as expected (unsurprising, as it doesn't use `:template-file` at all):
```lisp
  (setq org-capture-templates
        (doct `(
                ("Meeting Notes" :keys "m" :headline "Meetings"
                 :prepend t
                 :empty-lines 1
                 :clock-in t
                 :clock-resume t
                 :file "/tmp/meeting-notes-test.org"
                 :template ("* Meeting on %U"
                            ":PROPERTIES:"
                            ":ID: %(car (process-lines \"uuidgen\"))"
                            ":Created: %U"
                            ":END:"
                            "%?"))
                ("Web Pages" :keys "W" :headline "Website content"
                 :file "/tmp/website-test.org"
                 :template ("* Web entry on %U"
                            ":PROPERTIES:"
                            ":ID: %(car (process-lines \"uuidgen\"))"
                            ":Created: %U"
                            ":END:"
                            "%?")
                 :children (("jsturdy.github.io"  :keys "j" :headline "jsturdy.github.io")
                            ("sturdy.gitlab.io" :keys "c" :headline "sturdy.gitlab.com")))))))
```

#### Issue 1
Creating the two template files with content identical to the corresponding `:template` key from the above example, this works (though the 'm` capture uses the `W` `:template-file`):
```lisp
  (setq org-capture-templates
        (doct `(
                ("Meeting Notes" :keys "m" :headline "Meetings"
                 :prepend t
                 :empty-lines 1
                 :clock-in t
                 :clock-resume t
                 :file "/tmp/meeting-notes-test.org"
                 :template-file ,(expand-file-name "meeting-notes-template.org" my/org-template-dir))
                ("Web Pages" :keys "W" :headline "Website content"
                 :file "/tmp/website-test.org"
                 :template-file ,(expand-file-name "web-post-template.org" my/org-template-dir))
                 :children (("jsturdy.github.io"  :keys "j" :headline "jsturdy.github.io")
                            ("sturdy.gitlab.io" :keys "c" :headline "sturdy.gitlab.com")))))))
```
#### Interlude
Interestingly (based on what I observe in the last example below), this works fine as well:
```lisp
  (setq org-capture-templates
        (doct `(
                ("Meeting Notes" :keys "m" :headline "Meetings"
                 :prepend t
                 :empty-lines 1
                 :clock-in t
                 :clock-resume t
                 :file "/tmp/meeting-notes-test.org"
                 :template ("* Meeting on %U"
                            ":PROPERTIES:"
                            ":ID: %(car (process-lines \"uuidgen\"))"
                            ":Created: %U"
                            ":END:"
                            "%?"))
                ("Web Pages" :keys "W" :headline "Website content"
                 :file "/tmp/website-test.org"
                 :template-file ,(expand-file-name "web-post-template.org" my/org-template-dir))
                 :children (("jsturdy.github.io"  :keys "j" :headline "jsturdy.github.io")
                            ("sturdy.gitlab.io" :keys "c" :headline "sturdy.gitlab.com")))))))
```

#### Issue 2
But this results in the aforementioned error message `org-capture: Capture template ‘m’: Template is not a valid Org entry or tree`:
```lisp
  (setq org-capture-templates
        (doct `(
                ("Meeting Notes" :keys "m" :headline "Meetings"
                 :prepend t
                 :empty-lines 1
                 :clock-in t
                 :clock-resume t
                 :file "/tmp/meeting-notes-test.org"
                 :template-file ,(expand-file-name "meeting-notes-template.org" my/org-template-dir))
                ("Web Pages" :keys "W" :headline "Website content"
                 :file "/tmp/website-test.org"
                 :template ("* Web entry on %U"
                            ":PROPERTIES:"
                            ":ID: %(car (process-lines \"uuidgen\"))"
                            ":Created: %U"
                            ":END:"
                            "%?")
                 :children (("jsturdy.github.io"  :keys "j" :headline "jsturdy.github.io")
                            ("sturdy.gitlab.io" :keys "c" :headline "sturdy.gitlab.com")))))))
```

Hopefully this information is useful (and thanks for the tip about your open PR, I will have to check it out)

**Comment by progfolio** [comment] 2020-09-07 01:10
> Hopefully this information is useful

Useful, indeed. Thanks again. Pushed another patch that should work now. Let me know if it's still giving you trouble.

If you're interested in the details:

An internal function, `doct--first-in`, is usually used to look up  certain keywords when converting declarations to templates. It defaults to looking for keywords in an internal variable, `doct--current-plist`. After converting all declarations to templates, `doct--current-plist` contains the last declaration's plist (in your case the `W` declaration). This was being used at capture time instead of the appropriate plist for the current capture. So for your first case, it just happened to work because `W` has a `:template-file`. 

The second, `not a valid Org entry or tree` issue was caused by the same problem. `doct--fill-template` found a `:template-file` on the stale `W` declaration plist. Then it tried to pull `:template` from `m`. This returns `nil` since there is not `:template` for that declaration, `doct--fill-template` returns an empty string. `org-capture` tries to verify that the template string matches its entry type (`""` does not have a leading asterisk, so it's not a valid entry or tree).

The patch just passes the appropriate argument to `doct--first-in` so we get the plist we're interested in instead of a stale, unrelated one.

**Comment by jsturdy** [comment] 2020-09-07 06:36
Everything seems to be playing nicely together now.

Thanks for the quick work (and useful package)!

**Closed as completed** 2020-09-07 10:30 UTC
Labels: bug
