### ISSUE TITLE
issues with some completion packages?

### ISSUE THREAD

**Issue by mohkale** [progfolio/doct#5] opened 2020-02-02 23:00 UTC
using templates that contain the new `"%doct()"` construct causes an error to be thrown with the following functions.

- counsel-projectile-org-capture (from [counsel-projectile](https://github.com/ericdanan/counsel-projectile))

```elisp
Debugger entered--Lisp error: (wrong-type-argument symbolp (lambda nil (string-join (mapcar (function doct--fill-deferred-template) ("* %doct(todo-state) %?" "  %a")) "\n")))
  fboundp((lambda nil (string-join (mapcar (function doct--fill-deferred-template) ("* %doct(todo-state) %?" "  %a")) "\n")))
  org-capture-get-template()
  org-capture(nil "t")
  (closure (org-attach-directory org-indent-indentation-per-level org-indent-mode counsel-yank-pop-truncate-radius smex-ido-cache smex-initialized-p amx-cache amx-initialized info-lookup-mode t) (x) (org-capture nil (car (split-string x))))("t     Todo")
  ivy-call()
  ivy-read("Capture template: " ("p     [.emacs.d] Task" "t     Todo" "T     Todo with Clipboard" "h     Homework") :require-match t :action (closure (org-attach-directory org-indent-indentation-per-level org-indent-mode counsel-yank-pop-truncate-radius smex-ido-cache smex-initialized-p amx-cache amx-initialized info-lookup-mode t) (x) (org-capture nil (car (split-string x)))) :caller counsel-org-capture)
  counsel-org-capture()
  counsel-projectile-org-capture()
  funcall-interactively(counsel-projectile-org-capture)
  call-interactively(counsel-projectile-org-capture record nil)
  command-execute(counsel-projectile-org-capture record)
  counsel-M-x-action("counsel-projectile-org-capture")
  ivy-call()
  ivy-read("M-x " ("org-capture" "org-id-copy" "mohkale/find-capture-notes-file" "evil-version" "eshell" "haskell-repl" "describe-key" "keycast-mode" "haskell-indent-mode" "evil-multiedit" "flyspell-mode" "flyspell-correct-wrapper" "vertical-display-last-buffer" "counsel-evil-marks" "count-words" "hydra-flyspell/body" "which-key-mode" "kill-region" "prettify-symbols-mode" "server-start" "powerline-reset" "haskell-indentation-mode" "sort-lines" "pp-macroexpand-last-sexp" "ialign" "dired-omit-mode" "evil-snipe-mode" "display-last-buffer" "olivetti-mode" "python-repl" "counsel-package" "org-insert-item" "byte-compile-file" "package-refresh-contents" "rake" "ruby-mode" "package-install" "visual-line-mode" "copy-region-as-kill" "hl-highlight-thingatpt-local" "ivy-find-file-new-perspective" "lsp" "widen" "ansi-term" "html-mode" "fringe-mode" "show-prefix" "check-parens" "font-lock-mode" "hydra-visual-move/body" ...) :predicate (closure ((externs "org-capture" "org-id-copy" "mohkale/find-capture-notes-file" "evil-version" "eshell" "haskell-repl" "describe-key" "keycast-mode" "haskell-indent-mode" "evil-multiedit" "flyspell-mode" "flyspell-correct-wrapper" "vertical-display-last-buffer" "counsel-evil-marks" "count-words" "hydra-flyspell/body" "which-key-mode" "kill-region" "prettify-symbols-mode" "server-start" "powerline-reset" "haskell-indentation-mode" "sort-lines" "pp-macroexpand-last-sexp" "ialign" "dired-omit-mode" "evil-snipe-mode" "display-last-buffer" "olivetti-mode" "python-repl" "counsel-package" "org-insert-item" "byte-compile-file" "package-refresh-contents" "rake" "ruby-mode" "package-install" "visual-line-mode" "copy-region-as-kill" "hl-highlight-thingatpt-local" "ivy-find-file-new-perspective" "lsp" "widen" "ansi-term" "html-mode" "fringe-mode" "show-prefix" "check-parens" "font-lock-mode" ...) (initial-input) smex-ido-cache smex-initialized-p amx-cache amx-initialized info-lookup-mode t) (x) (not (get (intern x) (quote no-counsel-M-x)))) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (100663342 . counsel-find-symbol) (67108908 . counsel--info-lookup-symbol) (67108910 . hydra-ivy/body)) :initial-input nil :caller counsel-M-x)
  (let ((externs (counsel--M-x-externs))) (ivy-read (counsel--M-x-prompt) (or externs obarray) :predicate (if externs (function (lambda (x) (not (get (intern x) (quote no-counsel-M-x))))) (function (lambda (sym) (and (commandp sym) (not (get sym ...)) (not (get sym ...)))))) :require-match t :history (quote counsel-M-x-history) :action (function counsel-M-x-action) :keymap counsel-describe-map :initial-input initial-input :caller (quote counsel-M-x)))
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
```

- counsel-org-capture (from [counsel-org](https://github.com/abo-abo/swiper))

```elisp
Debugger entered--Lisp error: (wrong-type-argument symbolp (lambda nil (string-join (mapcar (function doct--fill-deferred-template) ("* %doct(todo-state) %?" "  %a")) "\n")))
  fboundp((lambda nil (string-join (mapcar (function doct--fill-deferred-template) ("* %doct(todo-state) %?" "  %a")) "\n")))
  org-capture-get-template()
  org-capture(nil "t")
  (closure (org-attach-directory org-indent-indentation-per-level org-indent-mode counsel-yank-pop-truncate-radius smex-ido-cache smex-initialized-p amx-cache amx-initialized info-lookup-mode t) (x) (org-capture nil (car (split-string x))))("t     Todo")
  ivy-call()
  ivy-read("Capture template: " ("t     Todo" "T     Todo with Clipboard" "h     Homework") :require-match t :action (closure (org-attach-directory org-indent-indentation-per-level org-indent-mode counsel-yank-pop-truncate-radius smex-ido-cache smex-initialized-p amx-cache amx-initialized info-lookup-mode t) (x) (org-capture nil (car (split-string x)))) :caller counsel-org-capture)
  counsel-org-capture()
  funcall-interactively(counsel-org-capture)
  call-interactively(counsel-org-capture record nil)
  command-execute(counsel-org-capture record)
  counsel-M-x-action("counsel-org-capture")
  ivy-call()
  ivy-read("M-x " ("counsel-org-capture" "counsel-projectile-org-capture" "org-capture" "org-id-copy" "mohkale/find-capture-notes-file" "evil-version" "eshell" "haskell-repl" "describe-key" "keycast-mode" "haskell-indent-mode" "evil-multiedit" "flyspell-mode" "flyspell-correct-wrapper" "vertical-display-last-buffer" "counsel-evil-marks" "count-words" "hydra-flyspell/body" "which-key-mode" "kill-region" "prettify-symbols-mode" "server-start" "powerline-reset" "haskell-indentation-mode" "sort-lines" "pp-macroexpand-last-sexp" "ialign" "dired-omit-mode" "evil-snipe-mode" "display-last-buffer" "olivetti-mode" "python-repl" "counsel-package" "org-insert-item" "byte-compile-file" "package-refresh-contents" "rake" "ruby-mode" "package-install" "visual-line-mode" "copy-region-as-kill" "hl-highlight-thingatpt-local" "ivy-find-file-new-perspective" "lsp" "widen" "ansi-term" "html-mode" "fringe-mode" "show-prefix" "check-parens" ...) :predicate (closure ((externs "counsel-org-capture" "counsel-projectile-org-capture" "org-capture" "org-id-copy" "mohkale/find-capture-notes-file" "evil-version" "eshell" "haskell-repl" "describe-key" "keycast-mode" "haskell-indent-mode" "evil-multiedit" "flyspell-mode" "flyspell-correct-wrapper" "vertical-display-last-buffer" "counsel-evil-marks" "count-words" "hydra-flyspell/body" "which-key-mode" "kill-region" "prettify-symbols-mode" "server-start" "powerline-reset" "haskell-indentation-mode" "sort-lines" "pp-macroexpand-last-sexp" "ialign" "dired-omit-mode" "evil-snipe-mode" "display-last-buffer" "olivetti-mode" "python-repl" "counsel-package" "org-insert-item" "byte-compile-file" "package-refresh-contents" "rake" "ruby-mode" "package-install" "visual-line-mode" "copy-region-as-kill" "hl-highlight-thingatpt-local" "ivy-find-file-new-perspective" "lsp" "widen" "ansi-term" "html-mode" "fringe-mode" "show-prefix" ...) (initial-input) smex-ido-cache smex-initialized-p amx-cache amx-initialized info-lookup-mode t) (x) (not (get (intern x) (quote no-counsel-M-x)))) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (100663342 . counsel-find-symbol) (67108908 . counsel--info-lookup-symbol) (67108910 . hydra-ivy/body)) :initial-input nil :caller counsel-M-x)
  (let ((externs (counsel--M-x-externs))) (ivy-read (counsel--M-x-prompt) (or externs obarray) :predicate (if externs (function (lambda (x) (not (get (intern x) (quote no-counsel-M-x))))) (function (lambda (sym) (and (commandp sym) (not (get sym ...)) (not (get sym ...)))))) :require-match t :history (quote counsel-M-x-history) :action (function counsel-M-x-action) :keymap counsel-describe-map :initial-input initial-input :caller (quote counsel-M-x)))
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
```

**Comment by progfolio** [comment] 2020-02-02 23:17
Thanks for the bug report. What version of Org mode are you using?

**Comment by mohkale** [comment] 2020-02-02 23:35
GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29

Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ c:/SP_CI_PROGRAMS/IDE/emacs/share/emacs/26.3/lisp/org/)

**Comment by progfolio** [comment] 2020-02-02 23:40
I'm 99% sure I know what the problem is. Just to confirm, does this work for you if you evaluate it in your scratch buffer?:
```elisp
(defun my/doct-todo ()
  (string-join '("* %doct(todo-state) %?" " %a") "\n"))

(let ((org-capture-templates
       (doct '(("Explicit function symbol"
                :keys "e"
                :todo-state "YES"
                :file ""
                :template my/doct-todo)))))
  (org-capture))
```
Should expand template in your default org notes file.

**Comment by mohkale** [comment] 2020-02-03 00:39
nope 😢.

```elisp
Debugger entered--Lisp error: (wrong-type-argument symbolp (lambda nil (doct--fill-deferred-template (funcall (function my/doct-todo)))))
  fboundp((lambda nil (doct--fill-deferred-template (funcall (function my/doct-todo)))))
  org-capture-get-template()
  org-capture()
  (let ((org-capture-templates (doct (quote (("Explicit function symbol" :keys "e" :todo-state "YES" :file "" :template my/doct-todo)))))) (org-capture))
  eval-buffer()  ; Reading at buffer position 443
  funcall-interactively(eval-buffer)
  call-interactively(eval-buffer nil nil)
  command-execute(eval-buffer)
```

**Comment by progfolio** [comment] 2020-02-03 00:44
I believe you're hitting an upstream bug in Org that I reported while writing doct. There was a check for `fboundp` in `org-capture-get-template` which has been changed to `functionp`. This predicate allows anonymous functions.  It should be patched in Org as of this commit: https://code.orgmode.org/bzg/org-mode/commit/b64a3308aa8d0008957f639d2910f5ff30ea5123

The reason you're hitting it is because templates utilizing the `%doct(KEYWORD)` syntax are expanded at capture time in an anonymous function call.

I'm working on a patch now. Upgrading Org mode past that patch would fix this, but I don't want to require that and can rework things so that I'm not passing a lambda to org-capture-get-template.

**Comment by progfolio** [comment] 2020-02-03 03:09
@mohkale Try this branch when you have time:
https://github.com/progfolio/doct/tree/bug-upstream-org-fboundp
Works for me on Org version 9.3, which still has the `fboundp` in `org-capture-get-template`. Hoping that works for you as well.

**Comment by mohkale** [comment] 2020-02-04 20:24
Yep, works perfectly, thnx 😄.

**Comment by progfolio** [comment] 2020-02-04 20:33
Excellent! Thanks again for the report. I've merged that branch into master.

**Closed as completed** 2020-02-04 20:33 UTC
Labels: bug
